// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type LandingPageDocumentDataSlicesSlice =
  | FormSectionSlice
  | FaqSectionSlice
  | BannerSlice
  | PartnershipsSlice
  | BenefitsSlice
  | AdvantagesSlice
  | SolutionSectionSlice
  | PlansSlice
  | BrandTrafficRiskSlice
  | HeroSectionSlice;

/**
 * Content for Landing Page documents
 */
interface LandingPageDocumentData {
  /**
   * Slice Zone field in *Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LandingPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

export type AllDocumentTypes = LandingPageDocument;

/**
 * Item in *Advantages → Default → Primary → Items*
 */
export interface AdvantagesSliceDefaultPrimaryItemsItem {
  /**
   * Item Title field in *Advantages → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *Advantages → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;
}

/**
 * Primary content in *Advantages → Default → Primary*
 */
export interface AdvantagesSliceDefaultPrimary {
  /**
   * Title field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Action Text field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;

  /**
   * Items field in *Advantages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<AdvantagesSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Advantages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdvantagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Advantages*
 */
type AdvantagesSliceVariation = AdvantagesSliceDefault;

/**
 * Advantages Shared Slice
 *
 * - **API ID**: `advantages`
 * - **Description**: Advantages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantagesSlice = prismic.SharedSlice<
  "advantages",
  AdvantagesSliceVariation
>;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Action Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Item in *Benefits → Default → Primary → Items*
 */
export interface BenefitsSliceDefaultPrimaryItemsItem {
  /**
   * Item Title field in *Benefits → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *Benefits → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;
}

/**
 * Primary content in *Benefits → Default → Primary*
 */
export interface BenefitsSliceDefaultPrimary {
  /**
   * Title field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Action Text field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;

  /**
   * Items field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<BenefitsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Item in *BrandTrafficRisk → Default → Primary → Items*
 */
export interface BrandTrafficRiskSliceDefaultPrimaryItemsItem {
  /**
   * Item Title field in *BrandTrafficRisk → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *BrandTrafficRisk → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;

  /**
   * Item Image field in *BrandTrafficRisk → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;
}

/**
 * Primary content in *BrandTrafficRisk → Default → Primary*
 */
export interface BrandTrafficRiskSliceDefaultPrimary {
  /**
   * Title field in *BrandTrafficRisk → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *BrandTrafficRisk → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Action Text field in *BrandTrafficRisk → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;

  /**
   * Items field in *BrandTrafficRisk → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_traffic_risk.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<BrandTrafficRiskSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for BrandTrafficRisk Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandTrafficRiskSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandTrafficRiskSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrandTrafficRisk*
 */
type BrandTrafficRiskSliceVariation = BrandTrafficRiskSliceDefault;

/**
 * BrandTrafficRisk Shared Slice
 *
 * - **API ID**: `brand_traffic_risk`
 * - **Description**: BrandTrafficRisk
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandTrafficRiskSlice = prismic.SharedSlice<
  "brand_traffic_risk",
  BrandTrafficRiskSliceVariation
>;

/**
 * Item in *FaqSection → Default → Primary → Items*
 */
export interface FaqSectionSliceDefaultPrimaryItemsItem {
  /**
   * Item Title field in *FaqSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Answer field in *FaqSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.items[].item_answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_answer: prismic.KeyTextField;
}

/**
 * Primary content in *FaqSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Title field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Items field in *FaqSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<FaqSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for FaqSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaqSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FaqSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FaqSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Primary content in *FormSection → Default → Primary*
 */
export interface FormSectionSliceDefaultPrimary {
  /**
   * Title field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Send Action Text field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.send_action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  send_action_text: prismic.KeyTextField;

  /**
   * Name Field Label field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.name_field_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_field_label: prismic.KeyTextField;

  /**
   * Name Field Placeholder field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.name_field_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_field_placeholder: prismic.KeyTextField;

  /**
   * Email Field Label field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.email_field_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_field_label: prismic.KeyTextField;

  /**
   * Email Field Placeholder field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.email_field_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_field_placeholder: prismic.KeyTextField;

  /**
   * Company Name Label field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.company_name_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name_label: prismic.KeyTextField;

  /**
   * Company Name Placeholder field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.company_name_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name_placeholder: prismic.KeyTextField;

  /**
   * Website Field Label field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.website_field_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_field_label: prismic.KeyTextField;

  /**
   * Website Field Placeholder field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.website_field_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_field_placeholder: prismic.KeyTextField;

  /**
   * Comment Field Label field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.comment_field_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  comment_field_label: prismic.KeyTextField;

  /**
   * Comment Field Placeholder field in *FormSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form_section.default.primary.comment_field_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  comment_field_placeholder: prismic.KeyTextField;
}

/**
 * Default variation for FormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormSection*
 */
type FormSectionSliceVariation = FormSectionSliceDefault;

/**
 * FormSection Shared Slice
 *
 * - **API ID**: `form_section`
 * - **Description**: FormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSectionSlice = prismic.SharedSlice<
  "form_section",
  FormSectionSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Action Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *Partnerships → Default → Primary → Items*
 */
export interface PartnershipsSliceDefaultPrimaryItemsItem {
  /**
   * Item Title field in *Partnerships → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *Partnerships → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;
}

/**
 * Item in *Partnerships → Default → Primary → Cards*
 */
export interface PartnershipsSliceDefaultPrimaryCardsItem {
  /**
   * Card Title field in *Partnerships → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.cards[].card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Description field in *Partnerships → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.cards[].card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_description: prismic.KeyTextField;
}

/**
 * Primary content in *Partnerships → Default → Primary*
 */
export interface PartnershipsSliceDefaultPrimary {
  /**
   * Label field in *Partnerships → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *Partnerships → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Items field in *Partnerships → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<PartnershipsSliceDefaultPrimaryItemsItem>>;

  /**
   * Cards field in *Partnerships → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partnerships.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<PartnershipsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Partnerships Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnershipsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnershipsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partnerships*
 */
type PartnershipsSliceVariation = PartnershipsSliceDefault;

/**
 * Partnerships Shared Slice
 *
 * - **API ID**: `partnerships`
 * - **Description**: Partnerships
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnershipsSlice = prismic.SharedSlice<
  "partnerships",
  PartnershipsSliceVariation
>;

/**
 * Item in *Plans → Default → Primary → Plans*
 */
export interface PlansSliceDefaultPrimaryPlansItem {
  /**
   * Plan Title field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].plan_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plan_title: prismic.KeyTextField;

  /**
   * Plan Description field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].plan_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plan_description: prismic.KeyTextField;

  /**
   * Plan Price field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].plan_price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  plan_price: prismic.RichTextField;

  /**
   * Plan Action Text field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].plan_action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plan_action_text: prismic.KeyTextField;

  /**
   * Plan Benefits List field in *Plans → Default → Primary → Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[].plan_benefits_list
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  plan_benefits_list: prismic.KeyTextField;
}

/**
 * Primary content in *Plans → Default → Primary*
 */
export interface PlansSliceDefaultPrimary {
  /**
   * Title field in *Plans → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Plans → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Action Text field in *Plans → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;

  /**
   * Plans field in *Plans → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: plans.default.primary.plans[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  plans: prismic.GroupField<Simplify<PlansSliceDefaultPrimaryPlansItem>>;
}

/**
 * Default variation for Plans Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlansSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlansSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Plans*
 */
type PlansSliceVariation = PlansSliceDefault;

/**
 * Plans Shared Slice
 *
 * - **API ID**: `plans`
 * - **Description**: Plans
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PlansSlice = prismic.SharedSlice<"plans", PlansSliceVariation>;

/**
 * Item in *SolutionSection → Default → Primary → Items*
 */
export interface SolutionSectionSliceDefaultPrimaryItemsItem {
  /**
   * Item Title field in *SolutionSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_section.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *SolutionSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_section.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;
}

/**
 * Primary content in *SolutionSection → Default → Primary*
 */
export interface SolutionSectionSliceDefaultPrimary {
  /**
   * Title field in *SolutionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SolutionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Action Text field in *SolutionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_section.default.primary.action_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  action_text: prismic.KeyTextField;

  /**
   * Items field in *SolutionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<
    Simplify<SolutionSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for SolutionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SolutionSection*
 */
type SolutionSectionSliceVariation = SolutionSectionSliceDefault;

/**
 * SolutionSection Shared Slice
 *
 * - **API ID**: `solution_section`
 * - **Description**: SolutionSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionSectionSlice = prismic.SharedSlice<
  "solution_section",
  SolutionSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LandingPageDocument,
      LandingPageDocumentData,
      LandingPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AdvantagesSlice,
      AdvantagesSliceDefaultPrimaryItemsItem,
      AdvantagesSliceDefaultPrimary,
      AdvantagesSliceVariation,
      AdvantagesSliceDefault,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BenefitsSlice,
      BenefitsSliceDefaultPrimaryItemsItem,
      BenefitsSliceDefaultPrimary,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      BrandTrafficRiskSlice,
      BrandTrafficRiskSliceDefaultPrimaryItemsItem,
      BrandTrafficRiskSliceDefaultPrimary,
      BrandTrafficRiskSliceVariation,
      BrandTrafficRiskSliceDefault,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryItemsItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FormSectionSlice,
      FormSectionSliceDefaultPrimary,
      FormSectionSliceVariation,
      FormSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      PartnershipsSlice,
      PartnershipsSliceDefaultPrimaryItemsItem,
      PartnershipsSliceDefaultPrimaryCardsItem,
      PartnershipsSliceDefaultPrimary,
      PartnershipsSliceVariation,
      PartnershipsSliceDefault,
      PlansSlice,
      PlansSliceDefaultPrimaryPlansItem,
      PlansSliceDefaultPrimary,
      PlansSliceVariation,
      PlansSliceDefault,
      SolutionSectionSlice,
      SolutionSectionSliceDefaultPrimaryItemsItem,
      SolutionSectionSliceDefaultPrimary,
      SolutionSectionSliceVariation,
      SolutionSectionSliceDefault,
    };
  }
}
