// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  advantages: dynamic(() => import("./Advantages")),
  banner: dynamic(() => import("./Banner")),
  benefits: dynamic(() => import("./Benefits")),
  brand_traffic_risk: dynamic(() => import("./BrandTrafficRisk")),
  hero_section: dynamic(() => import("./HeroSection")),
  partnerships: dynamic(() => import("./Partnerships")),
  plans: dynamic(() => import("./Plans")),
  solution_section: dynamic(() => import("./SolutionSection")),
};
