import type { Metadata } from "next";
import "@/styles/index.css";
import { themeClass } from "@/styles/theme.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={themeClass}>
      <body>{children}</body>
    </html>
  );
}
